// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBerCfyin8jsxA_4_rc0xDMi6xKWqsDNI',
    appId: '1:243911972207:web:09c74f700dcf6f16fec49a',
    messagingSenderId: '243911972207',
    projectId: 'fir-7b094',
    authDomain: 'fir-7b094.firebaseapp.com',
    storageBucket: 'fir-7b094.appspot.com',
    measurementId: 'G-Z5DC441Q0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgyoHxNWYfw7-KMbyyIBEMcVZ-4LgYfM',
    appId: '1:243911972207:android:cac9edbb5853c776fec49a',
    messagingSenderId: '243911972207',
    projectId: 'fir-7b094',
    storageBucket: 'fir-7b094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-8NC8n2u6GE-Avb5b_4OMMqo71DTXMY',
    appId: '1:243911972207:ios:44c8af721d4ee32cfec49a',
    messagingSenderId: '243911972207',
    projectId: 'fir-7b094',
    storageBucket: 'fir-7b094.appspot.com',
    iosBundleId: 'com.example.emailfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-8NC8n2u6GE-Avb5b_4OMMqo71DTXMY',
    appId: '1:243911972207:ios:fe0bb5ab442e768efec49a',
    messagingSenderId: '243911972207',
    projectId: 'fir-7b094',
    storageBucket: 'fir-7b094.appspot.com',
    iosBundleId: 'com.example.emailfirebase.RunnerTests',
  );
}
